apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: Sheharyar
  labels:
    app: stakaterimage
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: stakaterimage
    spec:
      containers:
      - image: stakaterimage:v1
        name: stakaterimage
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
